In [1]:
import cv2
import numpy as np
import os

In [2]:
def show(img):
    cv2.imshow("image",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [8]:
img = cv2.imread('images_1/img61.jpg')
print(img.shape)
img_1 = cv2.imread('images_1/Sample_Image.jpg')
# show(img_1)
print(img_1.shape)

img_2 = img_1[0::5,0::5]
print(img_2.shape)
# show(img_2)

img_3 = img_2[0:240]


(240, 320, 3)
(1263, 1600, 3)
(253, 320, 3)


In [9]:
img_g = cv2.imread('images_1/Sample_Image.jpg',0)
show(img_g)

img_g = img_g[0::5,0::5]
print(img_g.shape)
show(img_g)

img_g = img_g[0:240]
show(img_g)

(253, 320)


In [10]:
#mask w -> b
img_in = (img_g <= 230).astype('uint8')
print(img_in)
show(img_in)
img_in = np.stack((np.uint8(img_in),)*3, axis=-1)
img_mask = np.multiply(img_3,img_in)
show(img_mask)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [11]:
img_gb = (img_g >= 230).astype('uint8')
# img_gb.shape
# img_g.shape
img_c = np.stack((np.uint8(img_gb),)*3, axis=-1)
# show(img_c)
img_mul = np.multiply(img,img_c)
show(img_mul)
show(img_3)

In [12]:
img_com = np.add(img_mul,img_mask)
show(img_com)

In [193]:
cv2.imwrite("img_com.jpg",img_com)

True

In [110]:
print(img_mask.shape)
img_mask = img_3
white = (np.ones([240,320,3],dtype='uint8')*255)
img_mask = np.bitwise_and(white,img_3)
show(img_mask)
show(img_3)
show(np.ones([240,320,3],dtype='uint8')*255)

(240, 320, 3)


In [9]:
print(np.shape(img))
np.shape(img_1)

(240, 320, 3)


(1263, 1600, 3)

In [51]:
show(img_3)

In [58]:
img_2 = img_1[0::5,0::5]
print(img_2.shape)
show(img_2)

(253, 320, 3)


In [59]:
img_3 = img_2[0:240]

In [194]:
img_final = np.multiply(img,img_3)
img_final
# img_3
show(img&img_3)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]